site_name: MeshyDB
    
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - http
        - c#
        
nav:
    - index.md
    - getting started.md
    - API:
        - Authentication: api/auth.md
        - Users: api/users.md
        - Meshes: api/meshes.md

extra_css: 
    - css/syntaxhighlight.css
    - css/tabs.css
    - css/meshystyle.css
    
extra_javascript:
    - scripts/tabs.js
    
markdown_extensions:
    - markdown_fenced_code_tabs
