site_name: MeshyDB
    
theme: readthedocs
    
nav:
    - index.md
    - gettingstarted.md
    - API:
        - Authentication: api/auth.md
        - Users: api/users.md
        - Meshes: api/meshes.md

extra_css: 
    - css/syntaxhighlight.css
    - css/tabs.css
    
extra_javascript:
    - scripts/tabs.js
    
markdown_extensions:
    - markdown_fenced_code_tabs
